---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      box: TomKemperNL/xenial64

suites:
  - name: default
    run_list:
      - recipe[postgres-chef::default]
    verifier:
      inspec_tests:
        - test/integration
    attributes:
